#!/bin/bash

## AdGuard Home #在doh和dot中选一组延时最低
adguardhome_domestic_dns=(
    "https://doh.360.cn:443"
)
adguardhome_foreign_dns=(
    "h3://freedns.controld.com:443/p0"
)

## AdGuard Home (New) #写入所有测试可用的DNS服务器地址
adguardhome_new_domestic_dns=(
    "https://doh.360.cn:443"
    "tls://dot.360.cn:853"
    "https://doh.pub:443/dns-query"
    "tls://dot.pub:853"
    "tls://dot-pure.onedns.net:853"
    "h3://dns.alidns.com:443/dns-query"
    "tls://dns.alidns.com:853"
    "https://dns.alidns.com:443/dns-query"
    "https://doh-pure.onedns.net:443/dns-query"
)
adguardhome_new_foreign_dns=(
    "h3://freedns.controld.com:443/p0"
    "sdns://AQMAAAAAAAAAEzE0OS4xMTIuMTEyLjExOjg0NDMgZ8hHuMh1jNEgJFVDvnVnRt803x2EwAuMRwNo34Idhj4ZMi5kbnNjcnlwdC1jZXJ0LnF1YWQ5Lm5ldA"
    "quic://root.hagezi.org:853"
    "sdns://AQMAAAAAAAAAEjk0LjE0MC4xNC4xNDA6NTQ0MyC16ETWuDo-PhJo62gfvqcN48X6aNvWiBQdvy7AZrLa-iUyLmRuc2NyeXB0LnVuZmlsdGVyZWQubnMxLmFkZ3VhcmQuY29t"
    "sdns://AQIAAAAAAAAAFlsyYTEwOjUwYzA6OjE6ZmZdOjU0NDMgtehE1rg6Pj4SaOtoH76nDePF-mjb1ogUHb8uwGay2volMi5kbnNjcnlwdC51bmZpbHRlcmVkLm5zMS5hZGd1YXJkLmNvbQ"
    "sdns://AQMAAAAAAAAAFVsyNjIwOmZlOjpmZToxMV06ODQ0MyBnyEe4yHWM0SAkVUO-dWdG3zTfHYTAC4xHA2jfgh2GPhkyLmRuc2NyeXB0LWNlcnQucXVhZDkubmV0"
    "tls://dns-unfiltered.adguard.com:853"
    "sdns://AQMAAAAAAAAAElsyNjIwOmZlOjoxMV06ODQ0MyBnyEe4yHWM0SAkVUO-dWdG3zTfHYTAC4xHA2jfgh2GPhkyLmRuc2NyeXB0LWNlcnQucXVhZDkubmV0"
    "quic://wurzn.hagezi.org:853"
    "h3://wurzn.hagezi.org:443/dns-query"
    "tls://root.hagezi.org:853"
    "h3://9.9.9.11:443/dns-query"
    "h3://juuri.hagezi.org:443/dns-query"
    "tls://juuri.hagezi.org:853"
    "h3://149.112.112.11:443/dns-query"
    "h3://root.hagezi.org:443/dns-query"
    "tls://p0.freedns.controld.com:853"
    "quic://juuri.hagezi.org:853"
    "tls://wurzn.hagezi.org:853"
    "h3://[2620:fe::fe:11]:443/dns-query"
    "https://root.hagezi.org:443/dns-query"
    "https://wurzn.hagezi.org:443/dns-query"
    "https://juuri.hagezi.org:443/dns-query"
    "tls://wikimedia-dns.org:853"
    "h3://[2620:fe::11]:443/dns-query"
    "https://wikimedia-dns.org:443/dns-query"
)
